version: '3.8'

services:
  app:
    build: .
    container_name: python-web-app
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - app-network
    command: ["python", "main.py"]

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
    driver: local

networks:
  app-network:
    driver: bridge